FROM node:20-alpine

# Set the working directory
WORKDIR /app
# Copy package.json
COPY package.json .
# Install dependencies
ARG USE_PROXY=true
RUN if [ "$USE_PROXY" = "true" ]; then \
      npm config set https-proxy http://proxy2.gld.hksarg:8080 && \
      npm config set proxy http://proxy2.gld.hksarg:8080; \
    fi
RUN rm -rf node_modules && npm install

