FROM node:20-alpine

# Set the working directory
WORKDIR /app
# Copy package.json
COPY package.json .
# Install dependencies
RUN npm config set https-proxy http://proxy2.gld.hksarg:8080
RUN npm config set proxy http://proxy2.gld.hksarg:8080
RUN rm -rf node_modules && npm install

