name: Run Tests on Main Branch

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and run the test container
      - name: Run tests in Docker container
        run: |
          docker build --build-arg USE_PROXY=false -f Dockerfile.dev -t vueapp-test .
          docker run -v /app/node_modules -v .:/app vueapp-test npm run test -- run